### ISSUE TITLE
Error with Middle Click keybinds

### ISSUE THREAD

**Issue by Baylem** [anviaan/InventoryTweak#2]
### What happened?

It seems there is an issue binding this mods key bind to the middle mouse click. I've tested this mod with other mods and solo and I am unable to successfully get the middle click key bind to function

### Mod Version

2.5

### Minecraft Version

1.21

**Comment by Florke64** [comment]
It only listens for keyboard key press while the game doesn't block you from setting to mouse buttons. See [net.anvian.inventorytweaks.mixin.MixinKeyInputHandler](https://github.com/anviaan/InventoryTweak/blob/main/src/main/java/net/anvian/inventorytweaks/mixin/MixinKeyInputHandler.java)
